### PR TITLE
Customavatars

### PR DESCRIPTION
**Pull request by Goobwabber**
Adding support: #21 

this code still needs testing, and also dependencies need to be added to build

### CODE REVIEW

**Comment by Zingabopp** [comment]
Had to add a `using MultiplayerExtensions.Downloaders;` to MultiplayerInstaller.

**Comment by Zingabopp** [comment]
Also, this will break for anyone without CustomAvatars because `Harmony.PatchAll` looks through all classes and if CustomAvatars isn't there it's going to throw a `TypeLoadException`. You can work around this by applying each patch individually (you can see what I did in MultiplayerLite), which isn't too much of a hassle. You also can't touch any class with a member Type from CustomAvatars (fields, properties, functions).

I'm already planning on doing the Harmony stuff sometime soon to add Discord/Steam Rich Presence (probably just rip it from MPLite).

**Comment by Goobwabber** [comment]
I got the avatars spawning and everything, and they kind of track correctly, however, it seems like the arms and legs are being pulled in a separate direction from the head. I don't know much about how custom-avatars handles this stuff so I couldn't figure out why.

**Comment by Zingabopp** [comment]
I'm actually wondering if this should be a separate mod, like MultiplayerExtensions.CustomAvatars. It would make MultiplayerExtensions easier to maintain through updates to the game and/or CustomAvatars. Also, a good way to test how easy it is for other mods to interact with MultiplayerExtensions.

**Comment by Goobwabber** [comment]
I like this idea, I'll focus on getting a small API running and move this code into a different repository.

**Comment by Goobwabber** [comment]
This feature was moved to [Goobwabber/MultiplayerAvatars](https://github.com/Goobwabber/MultiplayerAvatars).

**Pull request closed without merging**
