### PR TITLE
v0.4.3

### PR DESCRIPTION
**Pull request by Goobwabber**
- Updated for BeatSaber 1.13.2
- API features (`MPEvents`/`MPState`)
- API documentation
- Cleaned up code
- Multiplayer Environment features
- Updated level entitlement to use base-game code

waiting on testing and beatsaversharp to merge

### CODE REVIEW

**Comment by BoingooTV** [comment]
i cant get this version to work :(

**Comment by aceadamuk** [comment]
is there anyway you can release this version? thanks

**Comment by Goobwabber** [comment]
For those of you watching this thread, I'm working on getting this update out today. Please be patient.

**Comment by aceadamuk** [comment]
> For those of you watching this thread, I'm working on getting this update out today. Please be patient.

thanks and good work on keeping the projects updated :)

**Comment by KretinD20** [comment]
you rock! was very sad for all the modders when they made the small update.

**Pull request merged**
